#!/bin/bash

test_results=$(node tests/game-sync-tests.js | grep "^TEST.*\$")
echo "${test_results}"

word_count_lines=$(echo "$test_results" | grep "^TEST.*FAIL\$" | wc -l)

if [[ ${word_count_lines} -gt 0 ]]; then
    exit 1;
fi
